# Generated by Django 5.2.16 on 2026-07-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orientacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='nivel',
        ),
    ]
