# Generated by Django 5.2.16 on 2026-07-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientacion', '0002_remove_expediente_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, verbose_name='motivo de la cancelación'),
        ),
    ]
