# Generated by Django 5.2.16 on 2026-07-15 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientacion', '0003_cita_motivo_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='psicologo_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'psicologo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='psicólogo asignado'),
        ),
    ]
